In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [3]:
!ln -s /content/drive/My\ Drive/ /my\drive

In [4]:
#파이토치 불러오기
!pip3 install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
!pip3 install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl

In [11]:
import torch

x = torch.tensor([[1,2,3], [4,5,6],[7,8,9]])
print(x)
print('Size:', x.size())
print('Shape:', x.shape)
print('Rank:', x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
Rank: 2


In [13]:
# 랭크 늘리기
# 텐서 첫째 자리(0번째)에 1차원 추가 [1,3,3] 형태의 랭크 3 텐서로 변환
# 랭크는 늘어나도 텐서 속 원소의 수는 유지

x = torch.unsqueeze(x,0)
print(x)
print('Size:', x.size())
print('Shape:', x.shape)
print("Rank:", x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Size: torch.Size([1, 3, 3])
Shape: torch.Size([1, 3, 3])
Rank: 3


In [14]:
# 랭크 줄이기
# 랭크는 줄어도 텐서 속 원소의 수는 유지
x = torch.squeeze(x,0)
print(x)
print('Size:', x.size())
print('Shape:', x.shape)
print("Rank:", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
Rank: 2


In [15]:
# 랭크의 형태 바꾸기
x = x.view(9)     # 랭크1의 텐서로 만들어 준다. 텐서 원소 갯수 변경은 안됨
print(x)
print('Size:', x.size)
print('Shape:', x.shape)
print('Rank:', x.ndimension())

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Size: <built-in method size of Tensor object at 0x7fe16ea01b40>
Shape: torch.Size([9])
Rank: 1


In [17]:
# 원소가 9개 텐서를 2*4 원소 8개로 변경 안됨
try:
  x = x.view(2,4)
except Exception as error:
  print(error)

shape '[2, 4]' is invalid for input of size 9


In [18]:
w = torch.randn(5,3, dtype=torch.float)
x = torch.tensor([[1.0,2.0], [3.0,4.0],[5.0,6.0]])
print('w size:', w.size())
print('x size:', x.size())
print('w:', w)
print('x:', x)

w size: torch.Size([5, 3])
x size: torch.Size([3, 2])
w: tensor([[-0.8645, -1.0214,  0.1251],
        [-1.1313, -1.7436,  0.2991],
        [-0.7851, -0.1579,  0.1118],
        [-0.6849, -1.0818,  0.0999],
        [-1.3017,  0.7618,  1.2240]])
x: tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [19]:
# 행렬 연산 위한 b 텐서 설정
b = torch.randn(5,2, dtype = torch.float)
print('b:', b.size())
print('b:', b)

b: torch.Size([5, 2])
b: tensor([[-1.9923, -0.7028],
        [ 0.6250, -0.2095],
        [ 0.6321, -0.2799],
        [ 0.3489, -1.0706],
        [-0.2726,  1.0314]])


In [21]:
# 행렬곱 수행
wx = torch.mm(w,x)     # w의 행은 5, x의 열은 2, 즉 shape는 [5,2]입니다.
print('wx size:', wx.size())
print('wx:', wx)

wx size: torch.Size([5, 2])
wx: tensor([[-3.3033, -5.0641],
        [-4.8668, -7.4426],
        [-0.6995, -1.5306],
        [-3.4308, -5.0976],
        [ 7.1036,  7.7877]])


In [22]:
result = wx+b
print('result size:', result.size())
print('result:', result)

result size: torch.Size([5, 2])
result: tensor([[-5.2956, -5.7669],
        [-4.2418, -7.6521],
        [-0.0673, -1.8105],
        [-3.0819, -6.1683],
        [ 6.8310,  8.8191]])
